version: "3"
services:
  grafana:
    image: grafana/grafana-oss:9.3.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  rhapi:
    build: ../apps/rhapi
    container_name: rhapi
    ports:
      - 8080:8080
