global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: rhapi
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'rhapi:8080'
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'